kind: Service
apiVersion: v1
metadata:
  name: hello-pks
spec:
  selector:
    app: hello-pks
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-pks
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-pks
    spec:
      containers:
      - name: hello-pks
        image: making/hello-pks:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: _JAVA_OPTIONS
          value: "-Xmx45M -Xss1M -XX:MaxMetaspaceSize=99M -XX:ReservedCodeCacheSize=32M -XX:CompressedClassSpaceSize=18M -XX:MaxDirectMemorySize=32M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Dinfo.docker.digest=INFO_DOCKER_DIGEST"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: CONTAINER_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: hello-pks
              resource: requests.cpu
        - name: CONTAINER_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: hello-pks
              resource: limits.cpu
        - name: CONTAINER_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: hello-pks
              resource: requests.memory
        - name: CONTAINER_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: hello-pks
              resource: limits.memory
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "256Mi"
          # requests:
          #   memory: "256Mi"